### ISSUE TITLE
Sending a notification with payload with Chrome intermittently fails

### ISSUE THREAD

**Issue by marco-c** [marco-c/web-push#117]
It fails when the base64-encoded `raw_data` contains characters that aren't standard base64.

E.g. it fails if `raw_data` is `31pPyH_6Y1qrYjMHxVsc-9eFqGPVgZ7J`, it succeeds if `raw_data` is `t7Aknp3CTVWO7akwPPX2FqMfAjuXVvB4`.

A simple fix is to use the base64 encoding instead of the URL-safe variant.

**Comment by beverloo** [comment]
Yup— `raw_data` has to be base64 (non-URL safe) when using the GCM protocol since it's not specific to Web Push, nor has any reason to use the URL safe alphabet by itself.
