### ISSUE TITLE
Support the new encryption standard in Firefox 46+

### ISSUE THREAD

**Issue by marco-c** [marco-c/web-push#120]
In Firefox 46-47 there's an intermediate standard with an auth secret of 12 bytes and `Content-Encoding: aesgcm128`, in Firefox 48+ the new standard is supported.

We should support both so that we can support VAPID also for notifications with payload.

**Comment by Minishlink** [comment]
Since the Mozilla push server's URL prefix is `https://updates.push.services.mozilla.com/push/v1/` right now, will Mozilla switch to another URL (eg with `v2`) when it will use the new standard ? That would be great in order to have backward compatibility.

**Comment by marco-c** [comment]
Unfortunately I don't think so, although @kitcambridge came up with a nice idea to detect `intermediate` vs `new`.

It's `intermediate` if the auth secret is 12 bytes long, `new` if 16.

**Comment by marco-c** [comment]
For reference: https://bugzilla.mozilla.org/show_bug.cgi?id=1257405 and https://bugzilla.mozilla.org/show_bug.cgi?id=1257821.

**Comment by Minishlink** [comment]
Yep that should do it, thanks!
