### ISSUE TITLE
Clarify format of userPublicKey and userAuth

### ISSUE THREAD

**Issue by owencm** [marco-c/web-push#142]
I'm not seeing data arriving in Chrome when passing into this library keys derived from `JSON.stringify(subscription)`. 

I presume instead I need to apply the `btoa(String.fromCharCode.apply(null, new Uint8Array(rawClientPublicKey)));` technique but that isn't documented here and the difference seems very subtle, e.g.:

In my experiment the `btoa` approach resulted in `BIG/OUeTvBk0tfplr+eNOh...` while `stringify` resulted in`BIG_OUeTvBk0tfplr-eNOh....`

Is there some specific requirement / can we somehow document this and make it well understood? (also bonus points for explaining the difference between these two and why it's only the symbols affected)

@beverloo @marco-c

**Comment by owencm** [comment]
It would also help if the library would do a sanity check on the keys and throw an error if they don't look vaguely plausible (correct encoding etc)

**Comment by owencm** [comment]
Ah, it seems like `stringify` is generating a [modified Base64 for URL variant](https://en.wikipedia.org/wiki/Base64#URL_applications) while `btoa` isn't. Can we detect the wrong encoding and throw a helpful error, or even accept either encoding?

**Comment by marco-c** [comment]
> accept either encoding?

This should already be the case, there are tests for both alternatives.
Could you show me your code?

This is working for me:
```JavaScript
  return fetch('/', {
    method: 'post',
    headers: {
      'Content-type': 'application/json'
    },
    body: JSON.stringify(subscription),
  });
```

```JavaScript
var obj = JSON.parse(body);
webPush.sendNotification(obj.endpoint, {
  payload: pushPayload,
  userPublicKey: obj.keys.p256dh,
  userAuth: obj.keys.auth,
});
```

**Comment by marco-c** [comment]
I've added some basic sanity checks with #144.

**Comment by marco-c** [comment]
Closing per http://stackoverflow.com/questions/36230214/keys-property-doesnt-exist-on-my-pushregistration-object/36230215?noredirect=1#comment60383312_36230215.
