### ISSUE TITLE
Error: Failed to translate Buffer to a EC_POINT

### ISSUE THREAD

**Issue by flintmedia** [marco-c/web-push#146]
Hi guys.. so in a bit of a noob in the encrypted web push scene. was just trying out the lib and encountered the error 'Error: Failed to translate Buffer to a EC_POINT' when the 'webPush.sendNotification(..' function is called on node 4.2 LTS. The push messages are not sent as a result. any ideas?

**Comment by marco-c** [comment]
Could you show me a snippet of your source code?
What browser are you using?

**Comment by flintmedia** [comment]
Sure! hows this?

`try{
webPush = require('web-push');
webPush.setGCMAPIKey('AIzaSyAMTL5G4ImT8w.....');
webPush.sendNotification(id, {
        TTL: 0,
        payload: '[{"user":"simon ..."}]',
        userPublicKey: '...',
        userAuth: '...',
      }).then(function(e) {
            console.log(e);
     }
}catch(err){

// [Error: Failed to translate Buffer to a EC_POINT]

}`

**Comment by marco-c** [comment]
It looks reasonable. Could you try updating to version 2.0.1 which has a few checks on the inputs?

**Comment by flintmedia** [comment]
oh wow! thanks now working fine after the update.. nextime ill update first before opening a new issue! Thanks for the lightning response though. may you live to have many bitcoins :)
