### ISSUE TITLE
Could payload encryption be optional?

### ISSUE THREAD

**Issue by jimmywarting** [marco-c/web-push#147]
We have both a android app and a web app.
We are in the transition of switching from [node-gcm](https://github.com/ToothlessGear/node-gcm) to just using only web-push (if possible)
It have come to my knowledge that chrome and android push is very much the same

From the Android app I was able to receive a token. I prefixed it with `https://android.googleapis.com/gcm/send/`and tried sending a push without a payload using web-push and it was a success. 
I even tried the reverse I took my token from chrome and putted it in [node-gcm](https://github.com/ToothlessGear/node-gcm) and stripped out the endpoint-prefix so I only had the token. And it also works!

With [node-gcm](https://github.com/ToothlessGear/node-gcm) we didn't have any `p256dh` or `auth` key. Only the token... but when i tried to send a payload with web-push it complains

```
Cannot read property 'length' of undefined
    at Object.decode (../node_modules/urlsafe-base64/lib/urlsafe-base64.js:53:29)
    at encryptOld (.../node_modules/web-push/index.js:64:57)
    at .../node_modules/web-push/index.js:168:23
    ...
```

Are the `p256dh` or `auth` key something Android can provide as well or is it only service worker related?

--
An other possible solution is not to send any payload at all, then we have fetch it our self in both the the Android app and the web using Ajax. then we don't need node-gcm any more, but that is not so trivial task

**Comment by marco-c** [comment]
>  It have come to my knowledge that chrome and android push is very much the same.

It is for now, but Chrome is going to switch to the standard Web Push protocol soon.
I don't know if their standard Web Push endpoints will support Android as well. @beverloo might know more.

**Comment by beverloo** [comment]
It works on any subscription, but you'll have to do the key generation and decryption parts yourself unfortunately. There might be a library for this at some point, but it's not something we're working on.

**Comment by marco-c** [comment]
So, a simple solution would be to use the push payload for web clients and to fetch the payload on Android clients.

**Comment by jimmywarting** [comment]
> So, a simple solution would be to use the push payload for web clients and to fetch the payload on Android clients.

That is one way to do it if you don't want to use any other libraries. But then you need to store the payload on the backend

**Comment by marco-c** [comment]
Another option is to do https://github.com/marco-c/web-push/issues/147#issuecomment-209002520, create the keys yourself in your Android client (like a Web Push client does).
Something like this:
```JavaScript
let userAuth = crypto.randomBytes(16);
let userCurve = crypto.createECDH('prime256v1');
let userPublicKey = userCurve.generateKeys();
let userPrivateKey = userCurve.getPrivateKey();
```

The client sends these values to the server, which sends a notification.

When the client receives the notification, it can decrypt it.

Which language are you using for the Android app? Java?

**Comment by jimmywarting** [comment]
Interesting!
Yep, I use java. I remember sending a another key/auth+payload to Android and was unable to decrypt it when it came through.

Could you show me an example on how to decrypt also? preferable in Java (but javascript could also be fine)

**Comment by marco-c** [comment]
Take a look at the `testEncrypt.js` test: https://github.com/marco-c/web-push/blob/master/test/testEncrypt.js.

I'm going to close the issue, since it isn't an issue, but feel free to keep commenting.
