### ISSUE TITLE
Facilitate send to Array of endpoints.

### ISSUE THREAD

**Issue by roylkng** [marco-c/web-push#160]
Can only send to single user, calling the send multiple times with same options is a waste of effort and resources.

**Comment by marco-c** [comment]
Push notifications can't be sent to multiple users at once, so it has to be implemented with a loop. Doing it in the library is the same as doing it in the application using the library.

**Comment by roylkng** [comment]
Hi Marco,

I think normal GCM allows push multicast up-to 1000 registration Ids, you
can check it here
<https://developers.google.com/cloud-messaging/http-server-ref#send-downstream>.
I don't check whether you guys are using the same GCM push API, so please
reassure me.

Thanks,
Rajan

**Comment by marco-c** [comment]
Chrome is currently using a proprietary protocol, but will soon switch to the Web Push standard which doesn't allow that.
