### ISSUE TITLE
Handling multiple subscribers at a time

### ISSUE THREAD

**Issue by anshulix** [marco-c/web-push#163]
In the use case I'm working, need to send gcm an array of subscriber ids. In web-push module, could this be supported by adding one more parameter of subscribers, and retrieving it here:

```

          var endpointSections = endpoint.split('/');
     //   var subscriptionId = endpointSections[endpointSections.length - 1];
          var subscribers = params.subscribers; 
     //   where subscribers in an array, and params just for understating purpose being put here.
        var gcmObj = {
          registration_ids: subscribers,
        };
```

**Comment by marco-c** [comment]
Unfortunately this isn't part of the Web Push standard, and Chrome is going to support the Web Push standard soon, so there's no point in supporting a non-standard feature that is going to be dropped soon.

**Comment by gauntface** [comment]
The web push protocol doesnt support sending multiple subscriptions in a single network call and chrome should be moving to an endpoint which uses the web push protocol soon

**Comment by anshulix** [comment]
Sending bulk push notifications would be a difficult task then. A call from subscriber/dashboard end to server, server to gcm and gcm to again subscriber, imagine for more than 10k subscribers and more. There has to be a middle way out.

**Comment by gauntface** [comment]
Please see the web push protocol doc for api:
https://tools.ietf.org/html/draft-ietf-webpush-protocol-02

Gcm api will not be used in the future.

**Comment by jakehm** [comment]
Any issue with this when you have a lot of subscriptions?

```
            for (const subscription of subscriptions) {
              webpush.sendNotification(
                subscription,
                message,
                options
              )
            }
```

**Comment by GauravSAdPushup** [comment]
Hi @jakehm, did the ``for of`` solution work out for you ? I am thinking of implementing something similar.

**Comment by eladnava** [comment]
@jakehm Yes, you should be `await`ing each of those `sendNotification` calls or using `async.series` to send X notifications at the same time. Otherwise, if you have 1,000 subscriptions, you will cause 1,000 sockets to be opened at once and this will most likely fail.

**Comment by bhawanisatnami007-sudo** [comment]
Hii
