### ISSUE TITLE
Don't work for me

### ISSUE THREAD

**Issue by jjgonver** [marco-c/web-push#167]
I'm trying the examples on https://serviceworke.rs/ with Google Chrome 51 and the next error appear:
POST https://serviceworke.rs/push-simple/sendNotification?endpoint=undefined&delay=5&ttl=0 503()
Thanks

**Comment by gauntface** [comment]
is this the right place for this bug? What made lead you to this page?

**Comment by marco-c** [comment]
I suggested https://serviceworke.rs/ as a source of examples for this library, but yes, this issue should be reported on https://github.com/mozilla/serviceworker-cookbook.

**Comment by jjgonver** [comment]
I'm looking for examples for web push with angular.
Thanks for your info.

**Comment by narendrasinghrathore** [comment]
@jjgonver Did you solve your issue, if yes please share. I am also facing same situation, Thanks.
