### ISSUE TITLE
Consider creating a web-push org?

### ISSUE THREAD

**Issue by gauntface** [marco-c/web-push#171]
@marco-c  There are few people that have reached out about sharing their implementation of the web push backend library, it would be great to have a canonical source for all of these.

Would you be open to creating a web-push org and donating this project to it?

I know @wibblymat is working on a Go implementation that he'd be up for putting under such an org and another developer of a Java implementation wanted to do a similar thing.

What do you think?

**Comment by marco-c** [comment]
Totally agree! It's what I suggested in https://github.com/GoogleChrome/web-push-encryption/issues/15#issuecomment-204017860.

There's also a Python implementation: https://github.com/mozilla-services/pywebpush.

**Comment by gauntface** [comment]
Sounds great, are you happy to create the org?

**Comment by marco-c** [comment]
OK, I'm going to call it `web-push-libs` (`web-push` is already taken).

**Comment by marco-c** [comment]
Done: https://github.com/web-push-libs.

**Comment by marco-c** [comment]
@Minishink would you like to move your PHP library to the new organization?
