### ISSUE TITLE
Make the test work under other platforms

### ISSUE THREAD

**Issue by zalun** [marco-c/web-push#46]
Currently tests are working on Linux.
I failed to make it work on OSX without changing selenium-init.js

**Comment by marco-c** [comment]
We need to update:
- test/selenium-init.js to download the correct binary according to the platform;
- test/selenium-chrome-init.js to write the Chrome policy file in the right path according to the platform.

**Comment by zalun** [comment]
We might use an optional parameter
node test/selenium-init.js {nameOfTheFileInfFtp}

**Comment by marco-c** [comment]
Doing it automatically would be better (so the developer wouldn't need to go look for the downloads by himself). If he needs to manually search the files, then he could just download the dependencies by himself without using the script.

We did something similar for PluotSorbet: https://github.com/mozilla/pluotsorbet/blob/master/Makefile#L207

**Comment by marco-c** [comment]
https://github.com/marco-c/web-push/pull/50 downloads automatically all the needed dependencies.

**Comment by marco-c** [comment]
@zalun are tests working for you now?

**Comment by marco-c** [comment]
I think they are working, reopen if they aren't.
