### ISSUE TITLE
Find a way to automatically dismiss the push notification prompt in Chromium on OS X

### ISSUE THREAD

**Issue by marco-c** [marco-c/web-push#51]
On Linux, I'm creating a policy file. On OS X creating a policy file is a little more complicated, I don't know if it's feasible on Travis.

**Comment by marco-c** [comment]
@gauntface do you have a better solution than what I'm using now?

**Comment by gauntface** [comment]
I'm currently doing this with: https://github.com/gauntface/simple-push-demo/blob/master/test/end-to-end.js#L66

Happy to add in as a PR, just let me know.

**Comment by marco-c** [comment]
That's great! This way the ugly script (`test/selenium-chrome-init.js`) to generate the policy file on Linux could be removed and the tests would work on OS X as well!

A PR would be greatly appreciated!

**Comment by gauntface** [comment]
Koolio will work on later today.

**Comment by gauntface** [comment]
This can probably be closed now.

**Comment by marco-c** [comment]
Yes, thank you!
