### ISSUE TITLE
Support requesting the removal of a subscription

### ISSUE THREAD

**Issue by marco-c** [marco-c/web-push#59]
https://tools.ietf.org/html/draft-ietf-webpush-protocol-00#section-7.3

**Comment by marco-c** [comment]
This is currently unsupported by the Firefox push service.

**Comment by kitcambridge** [comment]
I filed webpush-wg/webpush-protocol#86 to see how we should implement this, but it sounds like app servers shouldn't be able to remove subscriptions. Only browsers can do that.
