### ISSUE TITLE
Question: how to access notification payload when notification is clicked?

### ISSUE THREAD

**Issue by szimek** [marco-c/web-push#86]
Even though Firefox doesn't make it easy to test push notifications (why it doesn't allow them on localhost by default like Chrome?) I managed to send JSON payload and show custom title and message. In this payload I'm also sending a url, which I'd like to open when user clicks such notification. However, I can't figure out how to access this data. When I receive push notification, I get an instance of `PushEvent` and I can access the payload via `event.data.json()`. When a notification is clicked, I get an instance of `NotificationEvent` and I can access *some* data via `event.notification.data`, but in my case it's always `null`.

Is there some way to send a url that I can open when user clicks a notification?

I'm using the latest stable version of Firefox (44.0.2).

**Comment by marco-c** [comment]
The Push API works for me on localhost, I don't know why it doesn't work for you.

In one of my projects (https://github.com/mozilla/wp-web-push), I'm using the `data` property of the NotificationEvent.

In the `push` event handler:
```JavaScript
return self.registration.showNotification(data.title, {
  body: data.body,
  icon: data.icon,
  data: data,
});
```

In the `notificationclick` event handler:
```JavaScript
var data = event.notification.data;
var url = data.url;
```

**Comment by marco-c** [comment]
(I've closed the issue because it isn't actually an issue, but feel free to keep writing if you need something)

**Comment by szimek** [comment]
Thanks! Works perfectly.

One thing that was slightly confusing is that MDN docs for [showNotification](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) don't mention this `data` param, while MDN docs for [Notification()](https://developer.mozilla.org/en-US/docs/Web/API/Notification/Notification) do.

**Comment by marco-c** [comment]
Right, I've updated the documentation on MDN!

**Comment by Mengkhorn** [comment]
Thank it working perfectly.
