### ISSUE TITLE
doesn't work with http_ece-0.4.0

### ISSUE THREAD

**Issue by mplatov** [marco-c/web-push#87]
I was trying to use web-push with recently released http_ece-0.4.0 and it turns out it doesn't work - notification is accepted by Mozilla push service, but it didn't appear in Firefox, which makes me think that  Firefox couldn't decrypt the payload. 

Is it related to this issue? 
https://github.com/martinthomson/encrypted-content-encoding/issues/12

**Comment by marco-c** [comment]
@martinthomson are there API changes between http_ece 0.2.0 and 0.4.0?

**Comment by martinthomson** [comment]
Yeah, this is a change to the library to match the latest spec.  The size of the padding has changed.

If you have a flexible dependency, please fix it to 0.2.0 for the moment.  You will need 0.4.0 when we move to the aesgcm content encoding.

@marco-c, I didn't realize you had a dependency on this, so I apologize for the unannounced change.  Would it help if I provided you with a second interface that let you use the old version?

**Comment by marco-c** [comment]
> @marco-c, I didn't realize you had a dependency on this, so I apologize for the unannounced change. Would it help if I provided you with a second interface that let you use the old version?

No worries, I can pin to 0.2.0.

**Comment by martinthomson** [comment]
I've thought this through, you should be able to move to 0.4.1 when I release that.  I plan to add a padSize option so that you can get the same behaviour as with 0.2.0.  Then you have a transition strategy for when Firefox lands the new code.

**Comment by marco-c** [comment]
Fixed by https://github.com/marco-c/web-push/pull/90.
